# Generated by Django 5.0.6 on 2024-05-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0002_dataentry_delete_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataEntry',
            new_name='Data',
        ),
    ]
